#![deny(missing_docs)]
#![warn(clippy::all)]
//! Server-owned request-bound approval storage.
//!
//! Approval records are scoped to a tenant and originating identity. They bind a human decision
//! to one canonical server-built request envelope and policy version, then permit at most one
//! matching authorization consumption inside a SQLite transaction.

use std::fmt::Write as _;
use std::path::Path;
use std::sync::Mutex;

use rusqlite::{Connection, OptionalExtension};
use serde_json::Value;
use sha2::{Digest, Sha256};
use syntheos_contracts::{PrincipalId, TenantId};
use uuid::Uuid;

/// Maximum byte length accepted for an opaque authority record identity.
const MAX_TOKEN_IDENTITY_BYTES: usize = 36;
/// Maximum byte length accepted for a server-recognized tool name.
const MAX_TOOL_BYTES: usize = 128;
/// Maximum byte length accepted for a server-recognized action name.
const MAX_ACTION_BYTES: usize = 128;
/// Maximum byte length accepted for a human-facing approval prompt.
const MAX_PROMPT_BYTES: usize = 4096;
/// Maximum byte length accepted for a policy-version identifier.
const MAX_POLICY_VERSION_BYTES: usize = 128;
/// Maximum byte length accepted for a decision actor identifier.
const MAX_DECISION_ACTOR_BYTES: usize = 256;
/// Maximum byte length accepted for an optional decision reason.
const MAX_DECISION_REASON_BYTES: usize = 1024;
/// Maximum nested JSON value depth accepted by canonical request hashing.
pub const MAX_CANONICAL_JSON_DEPTH: usize = 128;

/// An approval-store operation failed.
#[derive(Debug, thiserror::Error)]
pub enum ApprovalError {
    /// SQLite could not complete a storage operation.
    #[error("approval storage error: {0}")]
    Storage(String),
    /// Caller supplied an invalid request, identifier, or decision value.
    #[error("invalid approval input: {0}")]
    InvalidInput(String),
    /// A database row violated a stored approval invariant.
    #[error("corrupt approval record: {0}")]
    Corrupt(String),
}

/// A request hash generated only from the server-built canonical envelope.
pub type RequestHash = [u8; 32];

/// The lifecycle state of one server-owned approval record.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApprovalStatus {
    /// The approval awaits a decision before its expiry time.
    Pending,
    /// The approval may be consumed once by its exact bound request.
    Approved,
    /// The approval was explicitly rejected and can never be consumed.
    Denied,
    /// The approval passed its time-to-live before a usable consumption.
    Expired,
    /// The approval authorization was consumed and cannot authorize another request.
    Consumed,
}

/// Convert an approval status to its stable SQLite token.
impl ApprovalStatus {
    /// Return the status token stored in SQLite.
    fn as_db(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::Approved => "approved",
            Self::Denied => "denied",
            Self::Expired => "expired",
            Self::Consumed => "consumed",
        }
    }

    /// Parse one status token persisted by this crate.
    fn from_db(value: &str) -> Result<Self, ApprovalError> {
        match value {
            "pending" => Ok(Self::Pending),
            "approved" => Ok(Self::Approved),
            "denied" => Ok(Self::Denied),
            "expired" => Ok(Self::Expired),
            "consumed" => Ok(Self::Consumed),
            _ => Err(ApprovalError::Corrupt(format!("unknown status {value:?}"))),
        }
    }
}

/// The decision a human operator can apply to a pending approval.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApprovalDecision {
    /// Permit one matching request consumption.
    Approve,
    /// Permanently reject the request.
    Deny,
}

/// The immutable server-built input used to create or retrieve a pending approval.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ApprovalRequest {
    /// Tenant that owns and scopes the request.
    pub tenant: TenantId,
    /// Principal that initiated the request.
    pub principal: PrincipalId,
    /// Authenticated token identity, not a cleartext credential.
    pub token_identity: String,
    /// Server-recognized tool name.
    pub tool: String,
    /// Server-recognized action name.
    pub action: String,
    /// SHA-256 fingerprint of the canonical server-built request envelope.
    pub request_hash: RequestHash,
    /// Human-facing prompt generated by the server for this request.
    pub prompt: String,
    /// Policy version evaluated by the server before requesting approval.
    pub policy_version: String,
    /// Unix timestamp at creation.
    pub created_at: i64,
    /// Unix timestamp at expiry.
    pub expires_at: i64,
}

/// A safely visible, request-bound approval record.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Approval {
    /// Stable approval record identifier.
    pub id: Uuid,
    /// Tenant that owns and scopes this record.
    pub tenant: TenantId,
    /// Principal that initiated the bound request.
    pub principal: PrincipalId,
    /// Authenticated token identity bound to the request.
    pub token_identity: String,
    /// Tool name bound to the approval.
    pub tool: String,
    /// Action name bound to the approval.
    pub action: String,
    /// SHA-256 fingerprint of the canonical server-built request envelope.
    pub request_hash: RequestHash,
    /// Human-facing decision prompt.
    pub prompt: String,
    /// Policy version bound to the approval.
    pub policy_version: String,
    /// Current immutable lifecycle status.
    pub status: ApprovalStatus,
    /// Unix timestamp at record creation.
    pub created_at: i64,
    /// Unix timestamp at record expiry.
    pub expires_at: i64,
    /// Unix timestamp at a human decision, when present.
    pub decided_at: Option<i64>,
    /// Unix timestamp at successful consumption, when present.
    pub consumed_at: Option<i64>,
    /// Decision actor identity, when a decision exists.
    pub decision_actor: Option<String>,
    /// Optional human decision reason.
    pub decision_reason: Option<String>,
}

/// A SQLite-backed authority approval store.
pub struct ApprovalStore {
    /// The isolated SQLite connection serialized for transaction integrity.
    conn: Mutex<Connection>,
}

/// Convert a rusqlite failure into a public approval-store error.
fn storage(error: rusqlite::Error) -> ApprovalError {
    ApprovalError::Storage(error.to_string())
}

/// Validate required request fields before any database mutation.
fn validate_request(request: &ApprovalRequest) -> Result<(), ApprovalError> {
    canonical_token_identity(&request.token_identity)?;
    if request.tool.is_empty()
        || request.tool.len() > MAX_TOOL_BYTES
        || request.action.is_empty()
        || request.action.len() > MAX_ACTION_BYTES
        || request.prompt.is_empty()
        || request.prompt.len() > MAX_PROMPT_BYTES
        || request.policy_version.is_empty()
        || request.policy_version.len() > MAX_POLICY_VERSION_BYTES
    {
        return Err(ApprovalError::InvalidInput(
            "request identity, tool, action, prompt, and policy version must be nonempty".into(),
        ));
    }
    if request.expires_at <= request.created_at {
        return Err(ApprovalError::InvalidInput(
            "approval expiry must be after creation".into(),
        ));
    }
    Ok(())
}

/// Parse and normalize an opaque UUID authority record identity, rejecting token-shaped values.
fn canonical_token_identity(value: &str) -> Result<String, ApprovalError> {
    if value.len() != MAX_TOKEN_IDENTITY_BYTES {
        return Err(ApprovalError::InvalidInput(
            "token identity must be a canonical UUID record identifier".into(),
        ));
    }
    let id = Uuid::parse_str(value).map_err(|_| {
        ApprovalError::InvalidInput(
            "token identity must be an opaque UUID record identifier".into(),
        )
    })?;
    if id.get_version_num() != 4 || id.to_string() != value {
        return Err(ApprovalError::InvalidInput(
            "token identity must be a canonical UUID v4 record identifier".into(),
        ));
    }
    Ok(id.to_string())
}

/// Convert a stored UUID text value into an approval identifier.
fn parse_uuid(value: String) -> Result<Uuid, ApprovalError> {
    Uuid::parse_str(&value).map_err(|error| ApprovalError::Corrupt(format!("invalid id: {error}")))
}

/// Convert a stored tenant text value into its strong contract type.
fn parse_tenant(value: String) -> Result<TenantId, ApprovalError> {
    value
        .parse()
        .map_err(|error| ApprovalError::Corrupt(format!("invalid tenant: {error}")))
}

/// Convert a stored principal text value into its strong contract type.
fn parse_principal(value: String) -> Result<PrincipalId, ApprovalError> {
    value
        .parse()
        .map_err(|error| ApprovalError::Corrupt(format!("invalid principal: {error}")))
}

/// Convert a stored 32-byte blob into a request hash.
fn parse_hash(value: Vec<u8>) -> Result<RequestHash, ApprovalError> {
    value
        .try_into()
        .map_err(|_| ApprovalError::Corrupt("request hash is not 32 bytes".into()))
}

/// Convert one approval to its read-time status without mutating durable terminal states.
fn effective_status(status: ApprovalStatus, expires_at: i64, now: i64) -> ApprovalStatus {
    if matches!(status, ApprovalStatus::Pending | ApprovalStatus::Approved) && expires_at <= now {
        ApprovalStatus::Expired
    } else {
        status
    }
}

/// Apply read-time expiry to one approval returned to callers.
fn with_effective_status(mut approval: Approval, now: i64) -> Approval {
    approval.status = effective_status(approval.status, approval.expires_at, now);
    approval
}

/// Return the current Unix timestamp in seconds for read-time expiry evaluation.
fn unix_seconds() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|duration| duration.as_secs().min(i64::MAX as u64) as i64)
        .unwrap_or(0)
}

/// Reconstruct an approval from the stable select column ordering used by this module.
fn approval_from_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Approval> {
    let convert = |error: ApprovalError| {
        rusqlite::Error::FromSqlConversionFailure(
            0,
            rusqlite::types::Type::Text,
            Box::new(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                error.to_string(),
            )),
        )
    };
    Ok(Approval {
        id: parse_uuid(row.get(0)?).map_err(convert)?,
        tenant: parse_tenant(row.get(1)?).map_err(convert)?,
        principal: parse_principal(row.get(2)?).map_err(convert)?,
        token_identity: row.get(3)?,
        tool: row.get(4)?,
        action: row.get(5)?,
        request_hash: parse_hash(row.get(6)?).map_err(convert)?,
        prompt: row.get(7)?,
        policy_version: row.get(8)?,
        status: ApprovalStatus::from_db(&row.get::<_, String>(9)?).map_err(convert)?,
        created_at: row.get(10)?,
        expires_at: row.get(11)?,
        decided_at: row.get(12)?,
        consumed_at: row.get(13)?,
        decision_actor: row.get(14)?,
        decision_reason: row.get(15)?,
    })
}

/// Stable column selection used for all approval reads.
const APPROVAL_COLUMNS: &str = "id, tenant_id, principal_id, token_identity, tool, action, request_hash, prompt, policy_version, status, created_at, expires_at, decided_at, consumed_at, decision_actor, decision_reason";

/// Append a depth-bounded canonical JSON representation sorted by UTF-8 object key bytes.
fn write_canonical_json(
    value: &Value,
    output: &mut String,
    depth: usize,
) -> Result<(), ApprovalError> {
    if depth > MAX_CANONICAL_JSON_DEPTH {
        return Err(ApprovalError::InvalidInput(format!(
            "JSON request envelope exceeds maximum depth {MAX_CANONICAL_JSON_DEPTH}"
        )));
    }
    match value {
        Value::Null => output.push_str("null"),
        Value::Bool(boolean) => output.push_str(if *boolean { "true" } else { "false" }),
        Value::String(string) => output
            .push_str(&serde_json::to_string(string).map_err(|error| {
                ApprovalError::InvalidInput(format!("invalid string: {error}"))
            })?),
        Value::Number(number) => {
            if let Some(float) = number.as_f64() {
                if !float.is_finite() {
                    return Err(ApprovalError::InvalidInput("non-finite JSON number".into()));
                }
            }
            output.push_str(&number.to_string());
        }
        Value::Array(values) => {
            output.push('[');
            for (index, item) in values.iter().enumerate() {
                if index != 0 {
                    output.push(',');
                }
                write_canonical_json(item, output, depth + 1)?;
            }
            output.push(']');
        }
        Value::Object(entries) => {
            output.push('{');
            let mut sorted = entries.iter().collect::<Vec<_>>();
            sorted.sort_unstable_by(|(left, _), (right, _)| left.as_bytes().cmp(right.as_bytes()));
            for (index, (key, item)) in sorted.into_iter().enumerate() {
                if index != 0 {
                    output.push(',');
                }
                output.push_str(&serde_json::to_string(key).map_err(|error| {
                    ApprovalError::InvalidInput(format!("invalid object key: {error}"))
                })?);
                output.push(':');
                write_canonical_json(item, output, depth + 1)?;
            }
            output.push('}');
        }
    }
    Ok(())
}

/// Compute a SHA-256 hash over a recursively canonicalized server-built JSON envelope.
pub fn canonical_request_hash(envelope: &Value) -> Result<RequestHash, ApprovalError> {
    let mut canonical = String::new();
    write_canonical_json(envelope, &mut canonical, 0)?;
    Ok(Sha256::digest(canonical.as_bytes()).into())
}

/// Return a lowercase hexadecimal string suitable for diagnostics without exposing request data.
pub fn request_hash_hex(hash: &RequestHash) -> String {
    let mut output = String::with_capacity(64);
    for byte in hash {
        let _ = write!(output, "{byte:02x}");
    }
    output
}

/// Applies the approval schema once to a fresh SQLite connection.
fn migrate(connection: &Connection) -> Result<(), ApprovalError> {
    connection
        .execute_batch(
            "CREATE TABLE IF NOT EXISTS approval (
                id TEXT PRIMARY KEY NOT NULL CHECK(length(id) = 36),
                tenant_id TEXT NOT NULL CHECK(length(tenant_id) = 36),
                principal_id TEXT NOT NULL CHECK(length(principal_id) = 36),
                token_identity TEXT NOT NULL CHECK(length(token_identity) = 36),
                tool TEXT NOT NULL CHECK(length(CAST(tool AS BLOB)) BETWEEN 1 AND 128),
                action TEXT NOT NULL CHECK(length(CAST(action AS BLOB)) BETWEEN 1 AND 128),
                request_hash BLOB NOT NULL CHECK(length(request_hash) = 32),
                prompt TEXT NOT NULL CHECK(length(CAST(prompt AS BLOB)) BETWEEN 1 AND 4096),
                policy_version TEXT NOT NULL CHECK(length(CAST(policy_version AS BLOB)) BETWEEN 1 AND 128),
                status TEXT NOT NULL CHECK(status IN ('pending', 'approved', 'denied', 'expired', 'consumed')),
                created_at INTEGER NOT NULL,
                expires_at INTEGER NOT NULL,
                decided_at INTEGER,
                consumed_at INTEGER,
                decision_actor TEXT CHECK(decision_actor IS NULL OR length(CAST(decision_actor AS BLOB)) BETWEEN 1 AND 256),
                decision_reason TEXT CHECK(decision_reason IS NULL OR length(CAST(decision_reason AS BLOB)) <= 1024)
            );
            CREATE INDEX IF NOT EXISTS approval_tenant_created_idx ON approval (tenant_id, created_at DESC);
            DROP INDEX IF EXISTS approval_pending_idempotency_idx;
            DROP INDEX IF EXISTS approval_idempotency_idx;
            CREATE UNIQUE INDEX IF NOT EXISTS approval_active_idempotency_idx
                ON approval (tenant_id, principal_id, token_identity, tool, action, request_hash, policy_version)
                WHERE status IN ('pending', 'approved');",
        )
        .map_err(storage)
}

/// Implements approval persistence and request-bound decision lifecycle operations.
impl ApprovalStore {
    /// Open a persistent approval database and apply the isolated schema.
    pub fn open(path: impl AsRef<Path>) -> Result<Self, ApprovalError> {
        let connection = Connection::open(path).map_err(storage)?;
        Self::from_connection(connection)
    }

    /// Open an in-memory approval database for tests and short-lived isolated use.
    pub fn open_in_memory() -> Result<Self, ApprovalError> {
        let connection = Connection::open_in_memory().map_err(storage)?;
        Self::from_connection(connection)
    }

    /// Apply the schema and construct a store around the supplied connection.
    fn from_connection(connection: Connection) -> Result<Self, ApprovalError> {
        connection
            .busy_timeout(std::time::Duration::from_secs(2))
            .map_err(storage)?;
        migrate(&connection)?;
        Ok(Self {
            conn: Mutex::new(connection),
        })
    }

    /// Create a pending approval or return the durable record for its exact idempotency key.
    pub fn create_or_get_pending(
        &self,
        request: ApprovalRequest,
        now: i64,
    ) -> Result<Approval, ApprovalError> {
        validate_request(&request)?;
        if request.expires_at <= now {
            return Err(ApprovalError::InvalidInput(
                "approval request is already expired".into(),
            ));
        }
        let mut connection = self.conn.lock().unwrap_or_else(|error| error.into_inner());
        let transaction = connection.transaction().map_err(storage)?;
        transaction.execute(
            "UPDATE approval SET status = 'expired' WHERE tenant_id = ?1 AND status IN ('pending', 'approved') AND expires_at <= ?2",
            rusqlite::params![request.tenant.to_string(), now],
        ).map_err(storage)?;
        let token_identity = canonical_token_identity(&request.token_identity)?;
        let select = format!("SELECT {APPROVAL_COLUMNS} FROM approval WHERE tenant_id = ?1 AND principal_id = ?2 AND token_identity = ?3 AND tool = ?4 AND action = ?5 AND request_hash = ?6 AND policy_version = ?7 ORDER BY created_at DESC, id DESC LIMIT 1");
        if let Some(existing) = transaction
            .query_row(
                &select,
                rusqlite::params![
                    request.tenant.to_string(),
                    request.principal.to_string(),
                    token_identity,
                    request.tool,
                    request.action,
                    request.request_hash.as_slice(),
                    request.policy_version
                ],
                approval_from_row,
            )
            .optional()
            .map_err(storage)?
        {
            if existing.status != ApprovalStatus::Expired {
                transaction.commit().map_err(storage)?;
                return Ok(existing);
            }
        }
        let approval = Approval {
            id: Uuid::new_v4(),
            tenant: request.tenant,
            principal: request.principal,
            token_identity,
            tool: request.tool,
            action: request.action,
            request_hash: request.request_hash,
            prompt: request.prompt,
            policy_version: request.policy_version,
            status: ApprovalStatus::Pending,
            created_at: request.created_at,
            expires_at: request.expires_at,
            decided_at: None,
            consumed_at: None,
            decision_actor: None,
            decision_reason: None,
        };
        let inserted = transaction.execute(
            "INSERT INTO approval (id, tenant_id, principal_id, token_identity, tool, action, request_hash, prompt, policy_version, status, created_at, expires_at) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, 'pending', ?10, ?11) ON CONFLICT DO NOTHING",
            rusqlite::params![approval.id.to_string(), approval.tenant.to_string(), approval.principal.to_string(), approval.token_identity, approval.tool, approval.action, approval.request_hash.as_slice(), approval.prompt, approval.policy_version, approval.created_at, approval.expires_at],
        ).map_err(storage)?;
        if inserted != 1 {
            let active_select = format!("SELECT {APPROVAL_COLUMNS} FROM approval WHERE tenant_id = ?1 AND principal_id = ?2 AND token_identity = ?3 AND tool = ?4 AND action = ?5 AND request_hash = ?6 AND policy_version = ?7 AND status IN ('pending', 'approved') ORDER BY created_at DESC, id DESC LIMIT 1");
            let existing = transaction
                .query_row(
                    &active_select,
                    rusqlite::params![
                        approval.tenant.to_string(),
                        approval.principal.to_string(),
                        approval.token_identity,
                        approval.tool,
                        approval.action,
                        approval.request_hash.as_slice(),
                        approval.policy_version
                    ],
                    approval_from_row,
                )
                .optional()
                .map_err(storage)?
                .ok_or_else(|| {
                    ApprovalError::Corrupt(
                        "approval insert conflicted without an active matching record".into(),
                    )
                })?;
            transaction.commit().map_err(storage)?;
            return Ok(existing);
        }
        transaction.commit().map_err(storage)?;
        Ok(approval)
    }

    /// Get one approval only when it belongs to the supplied tenant.
    pub fn get(&self, tenant: TenantId, id: Uuid) -> Result<Option<Approval>, ApprovalError> {
        let connection = self.conn.lock().unwrap_or_else(|error| error.into_inner());
        let statement =
            format!("SELECT {APPROVAL_COLUMNS} FROM approval WHERE tenant_id = ?1 AND id = ?2");
        connection
            .query_row(
                &statement,
                rusqlite::params![tenant.to_string(), id.to_string()],
                approval_from_row,
            )
            .optional()
            .map(|approval| {
                approval.map(|approval| with_effective_status(approval, unix_seconds()))
            })
            .map_err(storage)
    }

    /// List all approval records scoped to the supplied tenant, newest first.
    pub fn list(&self, tenant: TenantId) -> Result<Vec<Approval>, ApprovalError> {
        let connection = self.conn.lock().unwrap_or_else(|error| error.into_inner());
        let statement = format!(
            "SELECT {APPROVAL_COLUMNS} FROM approval WHERE tenant_id = ?1 ORDER BY created_at DESC"
        );
        let mut prepared = connection.prepare(&statement).map_err(storage)?;
        let rows = prepared
            .query_map(rusqlite::params![tenant.to_string()], approval_from_row)
            .map_err(storage)?;
        let now = unix_seconds();
        rows.map(|row| row.map(|approval| with_effective_status(approval, now)))
            .collect::<Result<Vec<_>, _>>()
            .map_err(storage)
    }

    /// Apply one decision only to a still-pending, non-expired record in the supplied tenant.
    pub fn decide(
        &self,
        tenant: TenantId,
        id: Uuid,
        decision: ApprovalDecision,
        actor: impl Into<String>,
        reason: Option<String>,
        now: i64,
    ) -> Result<Option<Approval>, ApprovalError> {
        let actor = actor.into();
        if actor.is_empty() || actor.len() > MAX_DECISION_ACTOR_BYTES {
            return Err(ApprovalError::InvalidInput(
                "decision actor must be nonempty".into(),
            ));
        }
        if reason
            .as_ref()
            .is_some_and(|value| value.len() > MAX_DECISION_REASON_BYTES)
        {
            return Err(ApprovalError::InvalidInput(
                "decision reason exceeds the maximum length".into(),
            ));
        }
        let mut connection = self.conn.lock().unwrap_or_else(|error| error.into_inner());
        let transaction = connection.transaction().map_err(storage)?;
        let statement =
            format!("SELECT {APPROVAL_COLUMNS} FROM approval WHERE tenant_id = ?1 AND id = ?2");
        let Some(mut approval) = transaction
            .query_row(
                &statement,
                rusqlite::params![tenant.to_string(), id.to_string()],
                approval_from_row,
            )
            .optional()
            .map_err(storage)?
        else {
            return Ok(None);
        };
        if approval.status != ApprovalStatus::Pending {
            return Ok(None);
        }
        if approval.expires_at <= now {
            transaction
                .execute(
                    "UPDATE approval SET status = 'expired' WHERE tenant_id = ?1 AND id = ?2 AND status = 'pending'",
                    rusqlite::params![tenant.to_string(), id.to_string()],
                )
                .map_err(storage)?;
            transaction.commit().map_err(storage)?;
            return Ok(None);
        }
        let status = match decision {
            ApprovalDecision::Approve => ApprovalStatus::Approved,
            ApprovalDecision::Deny => ApprovalStatus::Denied,
        };
        let changed = transaction.execute("UPDATE approval SET status = ?1, decided_at = ?2, decision_actor = ?3, decision_reason = ?4 WHERE tenant_id = ?5 AND id = ?6 AND status = 'pending'", rusqlite::params![status.as_db(), now, actor, reason, tenant.to_string(), id.to_string()]).map_err(storage)?;
        if changed != 1 {
            return Ok(None);
        }
        transaction.commit().map_err(storage)?;
        approval.status = status;
        approval.decided_at = Some(now);
        approval.decision_actor = Some(actor);
        approval.decision_reason = reason;
        Ok(Some(approval))
    }

    /// Mark all expired pending or approved records in one tenant as expired and return the count.
    pub fn expire(&self, tenant: TenantId, now: i64) -> Result<usize, ApprovalError> {
        let connection = self.conn.lock().unwrap_or_else(|error| error.into_inner());
        connection.execute("UPDATE approval SET status = 'expired' WHERE tenant_id = ?1 AND status IN ('pending', 'approved') AND expires_at <= ?2", rusqlite::params![tenant.to_string(), now]).map_err(storage)
    }

    /// Atomically consume approval authorization at most once when its bindings and TTL all match.
    pub fn consume_approved(
        &self,
        tenant: TenantId,
        id: Uuid,
        principal: PrincipalId,
        token_identity: &str,
        request_hash: &RequestHash,
        policy_version: &str,
        now: i64,
    ) -> Result<Option<Approval>, ApprovalError> {
        let token_identity = canonical_token_identity(token_identity)?;
        let mut connection = self.conn.lock().unwrap_or_else(|error| error.into_inner());
        let transaction = connection.transaction().map_err(storage)?;
        let statement =
            format!("SELECT {APPROVAL_COLUMNS} FROM approval WHERE tenant_id = ?1 AND id = ?2");
        let Some(mut approval) = transaction
            .query_row(
                &statement,
                rusqlite::params![tenant.to_string(), id.to_string()],
                approval_from_row,
            )
            .optional()
            .map_err(storage)?
        else {
            return Ok(None);
        };
        let exact_match = approval.status == ApprovalStatus::Approved
            && approval.expires_at > now
            && approval.principal == principal
            && approval.token_identity == token_identity
            && approval.request_hash == *request_hash
            && approval.policy_version == policy_version;
        if !exact_match {
            if approval.status == ApprovalStatus::Approved && approval.expires_at <= now {
                transaction.execute("UPDATE approval SET status = 'expired' WHERE tenant_id = ?1 AND id = ?2 AND status = 'approved'", rusqlite::params![tenant.to_string(), id.to_string()]).map_err(storage)?;
                transaction.commit().map_err(storage)?;
            }
            return Ok(None);
        }
        let changed = transaction.execute("UPDATE approval SET status = 'consumed', consumed_at = ?1 WHERE tenant_id = ?2 AND id = ?3 AND status = 'approved' AND expires_at > ?1", rusqlite::params![now, tenant.to_string(), id.to_string()]).map_err(storage)?;
        if changed != 1 {
            return Ok(None);
        }
        transaction.commit().map_err(storage)?;
        approval.status = ApprovalStatus::Consumed;
        approval.consumed_at = Some(now);
        Ok(Some(approval))
    }
}

/// Adversarial tests for canonical hashing and authority approval lifecycle invariants.
#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use serde_json::json;

    use super::*;

    /// Build a bounded server-owned request for lifecycle tests.
    fn request(tenant: TenantId, principal: PrincipalId, hash: RequestHash) -> ApprovalRequest {
        ApprovalRequest {
            tenant,
            principal,
            token_identity: Uuid::new_v4().to_string(),
            tool: "shell".into(),
            action: "exec".into(),
            request_hash: hash,
            prompt: "Run deployment command?".into(),
            policy_version: "v9".into(),
            created_at: 100,
            expires_at: 200,
        }
    }

    /// Build a JSON array nested exactly `depth` levels around a null leaf.
    fn nested_array(depth: usize) -> Value {
        let mut value = Value::Null;
        for _ in 0..depth {
            value = Value::Array(vec![value]);
        }
        value
    }

    /// Build a JSON object nested exactly `depth` levels around a null leaf.
    fn nested_object(depth: usize) -> Value {
        let mut value = Value::Null;
        for _ in 0..depth {
            let mut entries = serde_json::Map::new();
            entries.insert("child".into(), value);
            value = Value::Object(entries);
        }
        value
    }

    /// Return true when canonical hashing rejects an input as invalid.
    fn is_invalid_input(result: Result<RequestHash, ApprovalError>) -> bool {
        matches!(result, Err(ApprovalError::InvalidInput(_)))
    }

    /// Read the durable status token for one approval without applying read-time expiry.
    fn stored_status(store: &ApprovalStore, id: Uuid) -> ApprovalStatus {
        let connection = store.conn.lock().unwrap_or_else(|error| error.into_inner());
        connection
            .query_row(
                "SELECT status FROM approval WHERE id = ?1",
                rusqlite::params![id.to_string()],
                |row| {
                    ApprovalStatus::from_db(&row.get::<_, String>(0)?).map_err(|error| {
                        rusqlite::Error::FromSqlConversionFailure(
                            0,
                            rusqlite::types::Type::Text,
                            Box::new(std::io::Error::new(
                                std::io::ErrorKind::InvalidData,
                                error.to_string(),
                            )),
                        )
                    })
                },
            )
            .expect("stored status")
    }

    /// Object key order cannot alter the request fingerprint, while a semantic mutation does.
    #[test]
    fn canonical_hash_sorts_keys_and_detects_semantic_mutation() {
        let left =
            canonical_request_hash(&json!({"b": [true, null, 7], "a": {"z": "x", "y": false}}))
                .expect("hash");
        let reordered =
            canonical_request_hash(&json!({"a": {"y": false, "z": "x"}, "b": [true, null, 7]}))
                .expect("hash");
        let mutated =
            canonical_request_hash(&json!({"a": {"y": true, "z": "x"}, "b": [true, null, 7]}))
                .expect("hash");
        assert_eq!(left, reordered);
        assert_ne!(left, mutated);
    }

    /// Array canonicalization accepts the maximum documented depth and rejects one more level.
    #[test]
    fn canonical_hash_bounds_nested_arrays() {
        assert!(canonical_request_hash(&nested_array(MAX_CANONICAL_JSON_DEPTH)).is_ok());
        assert!(is_invalid_input(canonical_request_hash(&nested_array(
            MAX_CANONICAL_JSON_DEPTH + 1
        ))));
    }

    /// Object canonicalization accepts the maximum documented depth and rejects one more level.
    #[test]
    fn canonical_hash_bounds_nested_objects() {
        assert!(canonical_request_hash(&nested_object(MAX_CANONICAL_JSON_DEPTH)).is_ok());
        assert!(is_invalid_input(canonical_request_hash(&nested_object(
            MAX_CANONICAL_JSON_DEPTH + 1
        ))));
    }

    /// A decision is tenant-scoped and cannot be found by another tenant.
    #[test]
    fn cross_tenant_lookup_is_rejected() {
        let store = ApprovalStore::open_in_memory().expect("open");
        let tenant = TenantId::new();
        let approval = store
            .create_or_get_pending(request(tenant, PrincipalId::new(), [1; 32]), 101)
            .expect("create");
        assert!(store
            .get(TenantId::new(), approval.id)
            .expect("get")
            .is_none());
    }

    /// Creating a fresh approval in one tenant cannot mutate another tenant's expired row.
    #[test]
    fn lazy_expiry_is_scoped_to_the_request_tenant() {
        let store = ApprovalStore::open_in_memory().expect("open");
        let tenant_a = TenantId::new();
        let tenant_b = TenantId::new();
        let principal = PrincipalId::new();
        let stale = store
            .create_or_get_pending(request(tenant_b, principal, [13; 32]), 101)
            .expect("create stale tenant b approval");
        let mut fresh_request = request(tenant_a, principal, [14; 32]);
        fresh_request.created_at = 201;
        fresh_request.expires_at = 301;
        store
            .create_or_get_pending(fresh_request, 201)
            .expect("create tenant a approval");

        assert_eq!(stored_status(&store, stale.id), ApprovalStatus::Pending);
        assert_eq!(
            store
                .get(tenant_b, stale.id)
                .expect("read tenant b approval")
                .expect("tenant b approval")
                .status,
            ApprovalStatus::Expired
        );
    }

    /// Pending and approved records past their expiry read as expired.
    #[test]
    fn stale_pending_and_approved_records_read_as_expired() {
        let store = ApprovalStore::open_in_memory().expect("open");
        let tenant = TenantId::new();
        let principal = PrincipalId::new();
        let pending = store
            .create_or_get_pending(request(tenant, principal, [15; 32]), 101)
            .expect("create stale pending approval");
        let approved = store
            .create_or_get_pending(request(tenant, principal, [16; 32]), 101)
            .expect("create stale approved approval");
        store
            .decide(
                tenant,
                approved.id,
                ApprovalDecision::Approve,
                "operator",
                None,
                110,
            )
            .expect("approve stale approval");

        assert_eq!(
            store
                .get(tenant, pending.id)
                .expect("read pending")
                .expect("pending")
                .status,
            ApprovalStatus::Expired
        );
        assert_eq!(
            store
                .get(tenant, approved.id)
                .expect("read approved")
                .expect("approved")
                .status,
            ApprovalStatus::Expired
        );
        assert!(
            store
                .list(tenant)
                .expect("list")
                .into_iter()
                .filter(|approval| approval.status == ApprovalStatus::Expired)
                .count()
                >= 2
        );
    }

    /// Consumption refuses another principal even after a valid approval decision.
    #[test]
    fn cross_identity_use_is_rejected() {
        let store = ApprovalStore::open_in_memory().expect("open");
        let tenant = TenantId::new();
        let principal = PrincipalId::new();
        let approval = store
            .create_or_get_pending(request(tenant, principal, [2; 32]), 101)
            .expect("create");
        let token_identity = approval.token_identity.clone();
        store
            .decide(
                tenant,
                approval.id,
                ApprovalDecision::Approve,
                "operator",
                None,
                110,
            )
            .expect("decide")
            .expect("approved");
        assert!(store
            .consume_approved(
                tenant,
                approval.id,
                PrincipalId::new(),
                &token_identity,
                &[2; 32],
                "v9",
                120
            )
            .expect("consume")
            .is_none());
    }

    /// Denied and expired records never produce a successful consumption.
    #[test]
    fn denied_and_expired_approvals_cannot_be_used() {
        let store = ApprovalStore::open_in_memory().expect("open");
        let tenant = TenantId::new();
        let principal = PrincipalId::new();
        let denied = store
            .create_or_get_pending(request(tenant, principal, [3; 32]), 101)
            .expect("create");
        let denied_identity = denied.token_identity.clone();
        store
            .decide(
                tenant,
                denied.id,
                ApprovalDecision::Deny,
                "operator",
                None,
                110,
            )
            .expect("decide");
        assert!(store
            .consume_approved(
                tenant,
                denied.id,
                principal,
                &denied_identity,
                &[3; 32],
                "v9",
                120
            )
            .expect("consume")
            .is_none());
        let expired = store
            .create_or_get_pending(request(tenant, principal, [4; 32]), 101)
            .expect("create");
        let expired_identity = expired.token_identity.clone();
        store
            .decide(
                tenant,
                expired.id,
                ApprovalDecision::Approve,
                "operator",
                None,
                110,
            )
            .expect("decide");
        assert!(store
            .consume_approved(
                tenant,
                expired.id,
                principal,
                &expired_identity,
                &[4; 32],
                "v9",
                200
            )
            .expect("consume")
            .is_none());
    }

    /// Concurrent callers receive authorization consumption at most once.
    #[test]
    fn concurrent_consume_is_at_most_once() {
        let store = Arc::new(ApprovalStore::open_in_memory().expect("open"));
        let tenant = TenantId::new();
        let principal = PrincipalId::new();
        let approval = store
            .create_or_get_pending(request(tenant, principal, [5; 32]), 101)
            .expect("create");
        store
            .decide(
                tenant,
                approval.id,
                ApprovalDecision::Approve,
                "operator",
                None,
                110,
            )
            .expect("decide");
        let token_identity = approval.token_identity.clone();
        let mut handles = Vec::new();
        for _ in 0..8 {
            let store = Arc::clone(&store);
            let token_identity = token_identity.clone();
            handles.push(std::thread::spawn(move || {
                store
                    .consume_approved(
                        tenant,
                        approval.id,
                        principal,
                        &token_identity,
                        &[5; 32],
                        "v9",
                        120,
                    )
                    .expect("consume")
                    .is_some()
            }));
        }
        assert_eq!(
            handles
                .into_iter()
                .filter_map(|handle| handle.join().ok())
                .filter(|used| *used)
                .count(),
            1
        );
    }

    /// Denied and consumed request records are retained rather than recreated.
    #[test]
    fn terminal_request_cannot_be_recreated() {
        let store = ApprovalStore::open_in_memory().expect("open");
        let tenant = TenantId::new();
        let principal = PrincipalId::new();
        let denied_request = request(tenant, principal, [6; 32]);
        let approval = store
            .create_or_get_pending(denied_request.clone(), 101)
            .expect("create");
        store
            .decide(
                tenant,
                approval.id,
                ApprovalDecision::Deny,
                "operator",
                None,
                110,
            )
            .expect("decide");
        let replay = store
            .create_or_get_pending(denied_request, 111)
            .expect("replay");
        assert_eq!(replay.id, approval.id);
        assert_eq!(replay.status, ApprovalStatus::Denied);

        let consumed_request = request(tenant, principal, [9; 32]);
        let consumed = store
            .create_or_get_pending(consumed_request.clone(), 101)
            .expect("create consumed request");
        let consumed_identity = consumed.token_identity.clone();
        store
            .decide(
                tenant,
                consumed.id,
                ApprovalDecision::Approve,
                "operator",
                None,
                110,
            )
            .expect("approve consumed request");
        assert!(store
            .consume_approved(
                tenant,
                consumed.id,
                principal,
                &consumed_identity,
                &[9; 32],
                "v9",
                120,
            )
            .expect("consume")
            .is_some());
        let consumed_replay = store
            .create_or_get_pending(consumed_request, 121)
            .expect("replay consumed request");
        assert_eq!(consumed_replay.id, consumed.id);
        assert_eq!(consumed_replay.status, ApprovalStatus::Consumed);
    }

    /// An expired lifecycle permits one fresh pending approval for the same exact request.
    #[test]
    fn expired_request_can_start_one_fresh_approval_lifecycle() {
        let store = ApprovalStore::open_in_memory().expect("open");
        let tenant = TenantId::new();
        let principal = PrincipalId::new();
        let first_request = request(tenant, principal, [12; 32]);
        let first = store
            .create_or_get_pending(first_request.clone(), 101)
            .expect("create first approval");
        store
            .decide(
                tenant,
                first.id,
                ApprovalDecision::Approve,
                "operator",
                None,
                110,
            )
            .expect("approve first lifecycle");
        assert_eq!(
            store.expire(tenant, 200).expect("expire first lifecycle"),
            1
        );

        let mut renewed_request = first_request;
        renewed_request.created_at = 201;
        renewed_request.expires_at = 301;
        let renewed = store
            .create_or_get_pending(renewed_request.clone(), 201)
            .expect("create renewed approval");
        let duplicate = store
            .create_or_get_pending(renewed_request, 201)
            .expect("reuse active renewed approval");

        assert_ne!(renewed.id, first.id);
        assert_eq!(renewed.status, ApprovalStatus::Pending);
        assert_eq!(duplicate.id, renewed.id);
    }

    /// Separate connections return the same durable idempotency record for one exact request.
    #[test]
    fn independent_connections_share_idempotency_record() {
        let path = std::env::temp_dir().join(format!("henosis-approval-{}.sqlite", Uuid::new_v4()));
        let tenant = TenantId::new();
        let principal = PrincipalId::new();
        let request = request(tenant, principal, [7; 32]);
        let first = ApprovalStore::open(&path).expect("first open");
        let approval = first
            .create_or_get_pending(request.clone(), 101)
            .expect("first create");
        let second = ApprovalStore::open(&path).expect("second open");
        let replay = second
            .create_or_get_pending(request, 101)
            .expect("second create");
        assert_eq!(replay.id, approval.id);
        drop(second);
        drop(first);
        let _ = std::fs::remove_file(&path);
    }

    /// Token-shaped and oversized identities are rejected before persistence.
    #[test]
    fn token_identity_rejects_cleartext_credentials() {
        let store = ApprovalStore::open_in_memory().expect("open");
        let mut request = request(TenantId::new(), PrincipalId::new(), [8; 32]);
        request.token_identity = "hen_v1_aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa.secret".into();
        assert!(store.create_or_get_pending(request, 101).is_err());
    }

    /// Oversized request and decision strings are rejected before approval persistence.
    #[test]
    fn persisted_strings_are_bounded() {
        let store = ApprovalStore::open_in_memory().expect("open");
        let tenant = TenantId::new();
        let principal = PrincipalId::new();
        let mut oversized = request(tenant, principal, [10; 32]);
        oversized.prompt = "x".repeat(MAX_PROMPT_BYTES + 1);
        assert!(store.create_or_get_pending(oversized, 101).is_err());

        let approval = store
            .create_or_get_pending(request(tenant, principal, [11; 32]), 101)
            .expect("create");
        assert!(store
            .decide(
                tenant,
                approval.id,
                ApprovalDecision::Approve,
                "x".repeat(MAX_DECISION_ACTOR_BYTES + 1),
                None,
                110,
            )
            .is_err());
    }
}
